Class {
	#name : 'HfuSpManDontGetAngryOrder',
	#superclass : 'HfuSpGameOrder',
	#instVars : [
		'offset',
		'fieldID',
		'number',
		'hasFigures'
	],
	#category : 'HfuSpManDontGetAngry'
}

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> fieldID [

	^fieldID
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> fieldID: anObject [

	fieldID := anObject
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> hasFigures [

	^hasFigures
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> hasFigures: anObject [

	hasFigures := anObject
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> number [

	^number
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> number: anObject [

	number := anObject
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> offset [

	^offset
]

{ #category : 'Accessing' }
HfuSpManDontGetAngryOrder >> offset: anObject [

	offset := anObject
]
